one more import error(new)

Here is the error messages:
In [1]: import tensorflow
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a649b509054f> in <module>()
----> 1 import tensorflow

/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22 
---> 23 from tensorflow.python import *

/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py in <module>()
     96 from tensorflow.python.platform import resource_loader
     97 from tensorflow.python.platform import sysconfig
---> 98 from tensorflow.python.platform import test
     99 
    100 from tensorflow.python.util.all_util import make_all

/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/test.py in <module>()
     75 import sys
     76 if sys.version_info.major == 2:
---> 77   import mock                # pylint: disable=g-import-not-at-top,unused-import
     78 else:
     79   from unittest import mock  # pylint: disable=g-import-not-at-top

/usr/local/lib/python2.7/dist-packages/mock/__init__.py in <module>()
      1 from __future__ import absolute_import
----> 2 import mock.mock as _mock
      3 from mock.mock import *
      4 __all__ = _mock.__all__
      5 #import mock.mock as _mock

/usr/local/lib/python2.7/dist-packages/mock/mock.py in <module>()
     67 import six
     68 from six import wraps
---> 69 from pbr.version import VersionInfo
     70 
     71 _v = VersionInfo('mock').semantic_version()

ImportError: No module named pbr.version

Please help. According to the related no module alike errors I have updated the mock module and six(now 1.10.0), but the same error appears. Thanks very much.