Reshape cannot infer the missing input size for an empty tensor unless all specified

I trained faster-rcnn on coco dataset, when iter =11410, it appears a problem:
image: COCO_train2014_000000076146.jpg iter: 11410 / 200000, total loss: 3.3490, rpn_loss_cls: 0.7608, rpn_loss_box: 1.0145, loss_cls: 0.7640, loss_box: 0.8098, lr: 0.001000
speed: 0.327s / iter
2017-06-08 22:59:42.143627: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
[[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_131, gradients/TopKV2_grad/stack)]]
2017-06-08 22:59:42.143670: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
[[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_131, gradients/TopKV2_grad/stack)]]
2017-06-08 22:59:42.143965: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
[[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_131, gradients/TopKV2_grad/stack)]]
2017-06-08 22:59:42.144042: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
[[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_131, gradients/TopKV2_grad/stack)]]
2017-06-08 22:59:42.145758: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
[[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_131, gradients/TopKV2_grad/stack)]]
Traceback (most recent call last):
File "/home/yanchao/TFFRCNN/faster_rcnn/train_net.py", line 132, in
restore=bool(int(args.restore)))
File "/home/yanchao/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 400, in train_net
sw.train_model(sess, max_iters, restore=restore)
File "/home/yanchao/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 255, in train_model
cls_prob, bbox_pred, rois = sess.run(fetches=fetch_list, feed_dict=feed_dict)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
run_metadata_ptr)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
feed_dict_string, options, run_metadata)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
target_list, options, run_metadata)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
[[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_131, gradients/TopKV2_grad/stack)]]
Caused by op u'gradients/TopKV2_grad/Reshape', defined at:
File "/home/yanchao/TFFRCNN/faster_rcnn/train_net.py", line 132, in
restore=bool(int(args.restore)))
File "/home/yanchao/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 400, in train_net
sw.train_model(sess, max_iters, restore=restore)
File "/home/yanchao/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 142, in train_model
grads, norm = tf.clip_by_global_norm(tf.gradients(loss, tvars), 10.0)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 560, in gradients
grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 368, in _MaybeCompile
return grad_fn() # Exit early
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 560, in
grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_grad.py", line 577, in _TopKGrad
ind_2d = array_ops.reshape(op.outputs[1], array_ops.stack([-1, ind_lastdim]))
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2510, in reshape
name=name)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
op_def=op_def)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
original_op=self._default_original_op, op_def=op_def)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in init
self._traceback = _extract_stack()
...which was originally created as op u'TopKV2', defined at:
File "/home/yanchao/TFFRCNN/faster_rcnn/train_net.py", line 132, in
restore=bool(int(args.restore)))
[elided 0 identical lines from previous traceback]
File "/home/yanchao/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 400, in train_net
sw.train_model(sess, max_iters, restore=restore)
File "/home/yanchao/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 112, in train_model
self.net.build_loss(ohem=cfg.TRAIN.OHEM)
File "/home/yanchao/TFFRCNN/faster_rcnn/../lib/networks/network.py", line 643, in build_loss
rpn_cross_entropy_n_neg, _ = tf.nn.top_k(rpn_cross_entropy_n_neg, k=top_k)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1998, in top_k
return gen_nn_ops._top_kv2(input, k=k, sorted=sorted, name=name)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2502, in _top_kv2
name=name)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
op_def=op_def)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
original_op=self._default_original_op, op_def=op_def)
File "/home/yanchao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in init
self._traceback = _extract_stack()
InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
[[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_131, gradients/TopKV2_grad/stack)]]
Process finished with exit code 1
Does anyone meet the same things? Or this is a bug of tensorflow. It's really a strange problem.